// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag                  int32    `protobuf:"varint,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag                  int32    `protobuf:"varint,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0xdd, 0x0a, 0x82, 0x40,
	0x10, 0x85, 0x5b, 0xff, 0x1b, 0x2a, 0x62, 0x2e, 0x62, 0xe9, 0xca, 0xbc, 0xf2, 0x22, 0x24, 0xea,
	0x01, 0x7a, 0x87, 0xf5, 0x09, 0xb4, 0x1d, 0x44, 0x28, 0xd7, 0x9c, 0x35, 0xf0, 0xed, 0xc3, 0xc5,
	0x5e, 0xa0, 0xbb, 0x6f, 0x0e, 0x87, 0xe1, 0x7c, 0xb0, 0x7d, 0x11, 0x73, 0xd5, 0x50, 0xd1, 0x0f,
	0xc6, 0x9a, 0xec, 0x0e, 0xb1, 0xa2, 0xf7, 0x48, 0x6c, 0x71, 0x07, 0x5e, 0xab, 0xa5, 0x48, 0x45,
	0x1e, 0x2a, 0xaf, 0xd5, 0xb8, 0x07, 0xdf, 0x56, 0x8d, 0xf4, 0x5c, 0x30, 0x23, 0x22, 0x04, 0xb5,
	0xd1, 0x93, 0xf4, 0x53, 0x91, 0x6f, 0x94, 0xe3, 0xec, 0x09, 0x89, 0x22, 0xee, 0x4d, 0xc7, 0xf4,
	0xdf, 0x07, 0x3c, 0x40, 0xc4, 0xb6, 0xb2, 0x23, 0xcb, 0xc0, 0x15, 0x97, 0x6b, 0xee, 0xda, 0xa9,
	0x27, 0x19, 0xba, 0xd4, 0xf1, 0xf5, 0x0c, 0x71, 0x49, 0xc3, 0xa7, 0x7d, 0x10, 0x9e, 0x20, 0x28,
	0xa9, 0xd3, 0x98, 0x14, 0x8b, 0xc0, 0x71, 0x5d, 0xfc, 0x96, 0x64, 0xab, 0x5c, 0x5c, 0x44, 0x1d,
	0x39, 0xc7, 0xdb, 0x37, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x03, 0xd2, 0xed, 0xf4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Send(ctx context.Context, opts ...grpc.CallOption) (Service_SendClient, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Send(ctx context.Context, opts ...grpc.CallOption) (Service_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[0], "/Service/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceSendClient{stream}
	return x, nil
}

type Service_SendClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type serviceSendClient struct {
	grpc.ClientStream
}

func (x *serviceSendClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceSendClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Send(Service_SendServer) error
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Send(srv Service_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).Send(&serviceSendServer{stream})
}

type Service_SendServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type serviceSendServer struct {
	grpc.ServerStream
}

func (x *serviceSendServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceSendServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _Service_Send_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
